### ISSUE TITLE
There are documents missing

### ISSUE THREAD

**Issue by mlachance9** [PacktPublishing/Learning-Tableau-10.x#1]
Attached is one of the documents missing, Census data, that the instructor has us use.
[nst-est2017-01.xlsx](https://github.com/PacktPublishing/Learning-Tableau-10.x/files/6327140/nst-est2017-01.xlsx)

There are other files still missing: one for dates and one for visualization (color changes)

**Comment by Sonakshis** [comment]
Hi,
Thank you so much for bringing this to our attention. We have updated the repository with the latest US census data set.
Here is the link: https://github.com/PacktPublishing/Learning-Tableau-10.x/blob/7082b3ba255bce789404eebbe35c9a551a8cf5f4/US%20census,%20estimated%20population%20by%20state%202010-2019.xlsx

Happy learning!
